#pragma once

#include"GameObject.h"

#define MARIO_WALKING_SPEED 0.1f
#define MARIO_JUMP_SPEED_Y 0.5f
#define MARIO_GRAVITY 0.1f

#define MARIO_DIE_STATE 00

#define MARIO_SMALL_STATE 10
#define MARIO_SMALL_STATE_IDLE_LEFT 1001
#define MARIO_SMALL_STATE_IDLE_RIGHT 1002
#define MARIO_SMALL_STATE_WALKING_LEFT 1003
#define MARIO_SMALL_STATE_WALKING_RIGHT 1004
#define MARIO_SMALL_STATE_JUMP 1005

#define MARIO_SMALL_ANI_IDLE_LEFT 0
#define MARIO_SMALL_ANI_IDLE_RIGHT 1
#define MARIO_SMALL_ANI_WALKING_LEFT 2
#define MARIO_SMALL_ANI_WALKING_RIGHT 3
#define MARIO_SMALL_ANI_JUMP 4
#define MARIO_SMALL_DIE_ANI 5

#define MARIO_BIG_STATE 20
#define MARIO_BIG_STATE_IDLE_LEFT 2001
#define MARIO_BIG_STATE_IDLE_RIGHT 2002
#define MARIO_BIG_STATE_WALKING_LEFT 2003
#define MARIO_BIG_STATE_WALKING_RIGHT 2004
#define MARIO_BIG_STATE_JUMP 2005
#define MARIO_BIG_STATE_SIT 2006

#define MARIO_BIG_ANI_IDLE_LEFT 6
#define MARIO_BIG_ANI_IDLE_RIGHT 7
#define MARIO_BIG_ANI_WALKING_LEFT 8
#define MARIO_BIG_ANI_WALKING_RIGHT 9
#define MARIO_BIG_ANI_JUMP 10
#define MARIO_BIG_ANI_SIT 11

#define MARIO_FIRE_STATE 30
#define MARIO_FIRE_STATE_IDLE_LEFT 3001
#define MARIO_FIRE_STATE_IDLE_RIGHT 3002
#define MARIO_FIRE_STATE_WALKING_LEFT 3003
#define MARIO_FIRE_STATE_WALKING_RIGHT 3004
#define MARIO_FIRE_STATE_JUMP 3005
#define MARIO_FIRE_STATE_SIT 3006
#define MARIO_FIRE_STATE_SHOOT 3007

#define MARIO_FIRE_ANI_IDLE_LEFT 12
#define MARIO_FIRE_ANI_IDLE_RIGHT 13
#define MARIO_FIRE_ANI_WALKING_LEFT 14
#define MARIO_FIRE_ANI_WALKING_RIGHT 15
#define MARIO_FIRE_ANI_JUMP 16
#define MARIO_FIRE_ANI_SIT 17
#define MARIO_FIRE_ANI_SHOOT 18

#define MARIO_RACOON_STATE 40
#define MARIO_RACOON_STATE_IDLE_LEFT 4001
#define MARIO_RACOON_STATE_IDLE_RIGHT 4002
#define MARIO_RACOON_STATE_WALKING_LEFT 4003
#define MARIO_RACOON_STATE_WALKING_RIGHT 4004
#define MARIO_RACOON_STATE_JUMP 4005
#define MARIO_RACOON_STATE_SIT 4006
#define MARIO_RACOON_STATE_SHOOT 4007

#define MARIO_RACOON_ANI_IDLE_LEFT 19
#define MARIO_RACOON_ANI_IDLE_RIGHT 20
#define MARIO_RACOON_ANI_WALKING_LEFT 21
#define MARIO_RACOON_ANI_WALKING_RIGHT 22
#define MARIO_RACOON_ANI_JUMP 23
#define MARIO_RACOON_ANI_SIT 24
#define MARIO_RACOON_ANI_HIT 25

#define MARIO_STAR_STATE 50
#define MARIO_STAR_ANI_IDLE_LEFT 26
#define MARIO_STAR_ANI_IDLE_RIGHT 27
#define MARIO_STAR_ANI_WALKING_LEFT 28
#define MARIO_STAR_ANI_WALKING_RIGHT 29
#define MARIO_STAR_ANI_JUMP 30
#define MARIO_STAR_ANI_SIT 31


class Mario : public GameObject
{
public:
	void Update(DWORD dt);
	void Render();
	void SetState(int state);
};

