#pragma once

//id of texture
#define MARIO_TEXTURE "tex-mario"
#define BBOX_TEXTURE "tex-bbox"
#define ENEMY_TEXTURE "tex-enemy"
#define FIREBALL_TEXTURE "tex-fire-ball"
#define INTRO_TEXTURE "intro_texture"
#define MISC_TEXTURE "tex-misc"
#define UI_TEXTURE "tex-ui"

//gameobject types
#define PLAYER "Player"
#define ENEMY "Enemy"
#define GROUND "Ground"
#define FIRE "Fire"

#define MARIO_IDLE_STATE "IDLE"
#define MARIO_WALK_STATE "WALK"
#define MARIO_SKID_STATE "SKID"
#define MARIO_RUN_STATE "RUN"
#define MARIO_JUMP_STATE "JUMP"
#define MARIO_HIGH_JUMP_STATE "HIGH-JUMP"
#define MARIO_DIE_STATE "DIE"
#define MARIO_SLIDE_STATE "SLIDE"
#define MARIO_HOLD_MOVE_STATE "HOLD-MOVE"
#define MARIO_HOLE_IDLE_STATE "HOLD-IDLE"
#define MARIO_KICK_STATE "KICK"
#define MARIO_DIVE_STATE "DIVE"
#define MARIO_SWIM_STATE "SWIM"
#define MARIO_CLIMB_STATE "CLIMB"
#define MARIO_SIT_STATE "SIT"
#define MARIO_ATTACK_STATE "ATTACK"
#define MARIO_FLY_STATE "FLY"
#define MARIO_ROLL_STATE "ROLL"
#define MARIO_SIT_STATE "SIT"
#define MARIO_KICK_STATE "KICK"
#define MARIO_IDLE_FRONT_STATE "IDLE-FRONT"